### ISSUE TITLE
Docker Hub Organization Name?

### ISSUE THREAD

**Issue by oxr463** [openwrt/docker#1]
Why `openwrtorg`, instead of `openwrt`?

**Comment by aparcar** [comment]
I think openwrt was already taken, maybe it is possible to reclaim it.

**Comment by aparcar** [comment]
I don't seem to find a way to contact the docker team about this, you got an idea?

**Comment by oxr463** [comment]
The [page](https://hub.docker.com/_/openwrt) returns a 404 for me. Perhaps it is reserved, since it resides in the global namespace?

**Comment by aparcar** [comment]
Fixed, we now own `openwrt`.
