### ISSUE TITLE
procd: Hangs on shutdown in docker

### ISSUE THREAD

**Issue by mikma** [openwrt/docker#15]
I added a procd bug report related to Docker.

https://bugs.openwrt.org/index.php?do=details&task_id=2425

**Comment by aparcar** [comment]
To fix this I'll port [this patch](https://github.com/mikma/lxd-openwrt/blob/master/patches/procd-master/0003-docker-fix-problem-stopping-container.patch) to procd.

**Comment by aparcar** [comment]
Fixed via https://github.com/openwrt/openwrt/commit/d9364c1cbc6a13f1dc2ea8432c98962ed157991f
