### ISSUE TITLE
example for gitlab-ci

### ISSUE THREAD

**Issue by stefangweichinger** [openwrt/docker#91]
I am looking for an example how to use the image-builder docker image in a GitLab CI/CD pipeline.
Could anyone post one or add a link/pointer here? Thanks a lot.

**Comment by aparcar** [comment]
https://github.com/openwrt/docker/blob/master/.gitlab/ci/imagebuilder.yml#L13

**Comment by stefangweichinger** [comment]
As far as I understand the quoted yml builds the image-builder docker image, right?
I am looking for an example how to *use* that docker image inside a build pipeline to actually build openwrt-image-files.

Maybe I misunderstand, pls advise.

**Comment by ynezz** [comment]
> As far as I understand the quoted yml builds the image-builder docker image, right?

No. See https://hub.docker.com/r/openwrtorg/imagebuilder or https://github.com/openwrt/docker#imagebuilder for another example, there is documentation as well https://openwrt.org/docs/guide-user/additional-software/imagebuilder. This is not a support channel, only bug reports are expected, for such basic support questions please use [forums](https://forum.openwrt.org/c/devel/8) instead.

**Comment by stefangweichinger** [comment]
thx
