### ISSUE TITLE
tag ramips-mt7621-22.03.2 is same as ramips-mt7620-22.03.2

### ISSUE THREAD

**Issue by zhengmz** [openwrt/docker#96]
At <https://hub.docker.com/r/openwrtorg/sdk>, tag ramips-mt7621-22.03.2 is same as ramips-mt7620-22.03.2

Please check and repaid it, thanks.

![image](https://user-images.githubusercontent.com/3997518/207542594-92f260f0-e828-46bb-9738-4689fffb8c5c.png)

**Comment by aparcar** [comment]
This is not a bug: Targets may use the same architecture and can therefore use the same SDK. To same bandwidth the SDKs are tagged with multiple labels, the architecture itself and each target that is supported.

```shell
./scripts/dump-target-info.pl architectures | grep mt7621
mipsel_24kc ramips/mt7620 ramips/mt7621 ramips/mt76x8 ramips/rt288x ramips/rt305x
```
