### ISSUE TITLE
Dockerfile: add "feeds.conf" to "imagebuilder" too

### ISSUE THREAD

**Issue by lars18th** [openwrt/docker#97]
Hi,

The official docker image could be used with the feed scripts (`./scripts/feeds`) to compile custom packages. However, is quite annoying that the small text file `feeds.conf` is missing. And this generates a lot of troubles if you don't know why the docker image fails to execute the feed scripts.

So, I suggest to add the default file described in the documentation (https://openwrt.org/docs/guide-developer/feeds):
```
src-git packages https://git.openwrt.org/feed/packages.git
src-git luci https://git.openwrt.org/project/luci.git
src-git routing https://git.openwrt.org/feed/routing.git
src-git telephony https://git.openwrt.org/feed/telephony.git
#src-git video https://github.com/openwrt/video.git
#src-git targets https://github.com/openwrt/targets.git
#src-git management https://github.com/openwrt-management/packages.git
#src-git oldpackages http://git.openwrt.org/packages.git
#src-link custom /usr/src/openwrt/custom-feed
```

I hope you agree with that.
Regards.

**Comment by aparcar** [comment]
You can't compile packages with the imagebuilder but only the SDK, why would you want feeds (aka uncompiled package definitions) in the ImageBuidler?

**Comment by lars18th** [comment]
Yes, you're right. Only the SDK could be used to compile packages.

Perhaps this sounds stupid, but I suggest to put some README file inside the "imagebuilder" container image to describe the "target use". And recommend inside it to use the "SDK" to compile packages. I feel other users will be confused by the different images.

Anyway I close this issue.
Thank you @aparcar.
