### ISSUE TITLE
Why do snapshot images stop receiving updates?

### ISSUE THREAD

**Issue by MoetaYuko** [openwrt/docker#98]
snapshot images at https://registry.hub.docker.com/r/openwrt/sdk/tags?page=1&name=snapshot should be updated every day, but the last update dates are all Feb 19, what happened?

cc: @aparcar

**Comment by ynezz** [comment]
master snapshots are build every two days, 22.03 snapshots are build weekly, 21.05 snapshots monthly.

**Comment by MoetaYuko** [comment]
Oh, thanks for the clarification.
